spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-batch?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root@root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    #      hibernate:
    #        format_sql: true
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

# job.enabled will not start the batch processing, batch will start after hitting the endpoint
# jdbc.initialize-schema = it will create other tables in database to store the states